# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/lua/lua-cmsgpack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/lua/lua-cmsgpack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/lua/lua-cmsgpack/CMakeFiles /mnt/d/lua/lua-cmsgpack/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/lua/lua-cmsgpack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmsgpack

# Build rule for target.
cmsgpack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmsgpack
.PHONY : cmsgpack

# fast build rule for target.
cmsgpack/fast:
	$(MAKE) -f CMakeFiles/cmsgpack.dir/build.make CMakeFiles/cmsgpack.dir/build
.PHONY : cmsgpack/fast

#=============================================================================
# Target rules for targets named msgpack-build

# Build rule for target.
msgpack-build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msgpack-build
.PHONY : msgpack-build

# fast build rule for target.
msgpack-build/fast:
	$(MAKE) -f CMakeFiles/msgpack-build.dir/build.make CMakeFiles/msgpack-build.dir/build
.PHONY : msgpack-build/fast

#=============================================================================
# Target rules for targets named msgpack

# Build rule for target.
msgpack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msgpack
.PHONY : msgpack

# fast build rule for target.
msgpack/fast:
	$(MAKE) -f CMakeFiles/msgpack.dir/build.make CMakeFiles/msgpack.dir/build
.PHONY : msgpack/fast

lua_cmsgpack.o: lua_cmsgpack.c.o

.PHONY : lua_cmsgpack.o

# target to build an object file
lua_cmsgpack.c.o:
	$(MAKE) -f CMakeFiles/cmsgpack.dir/build.make CMakeFiles/cmsgpack.dir/lua_cmsgpack.c.o
.PHONY : lua_cmsgpack.c.o

lua_cmsgpack.i: lua_cmsgpack.c.i

.PHONY : lua_cmsgpack.i

# target to preprocess a source file
lua_cmsgpack.c.i:
	$(MAKE) -f CMakeFiles/cmsgpack.dir/build.make CMakeFiles/cmsgpack.dir/lua_cmsgpack.c.i
.PHONY : lua_cmsgpack.c.i

lua_cmsgpack.s: lua_cmsgpack.c.s

.PHONY : lua_cmsgpack.s

# target to generate assembly for a file
lua_cmsgpack.c.s:
	$(MAKE) -f CMakeFiles/cmsgpack.dir/build.make CMakeFiles/cmsgpack.dir/lua_cmsgpack.c.s
.PHONY : lua_cmsgpack.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cmsgpack"
	@echo "... msgpack-build"
	@echo "... msgpack"
	@echo "... lua_cmsgpack.o"
	@echo "... lua_cmsgpack.i"
	@echo "... lua_cmsgpack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

